### ISSUE TITLE
Create stub package published to PyPI named `geoarrow`

### ISSUE THREAD

**Issue by kylebarron** [geoarrow/geoarrow-python#3]
Aimed to prevent a future package from breaking our native namespacing by distributing a top-level `geoarrow/__init__.py`

**Comment by jorisvandenbossche** [comment]
Longer term this could also be a "meta" package that installs all separate pieces?

**Comment by kylebarron** [comment]
Yeah definitely! If you want the entire ecosystem, just `pip install geoarrow` (similar to `pip install jupyter`). Otherwise, install `geoarrow-c` or `geoarrow-rs` or whatever directly
